baseURL = 'https://sukonbu.party/'
languageCode = 'en-us'
title = 'Sukonbu'
theme = 'hugo-bearcub'
themeStyle = "original"
author = 'Sukonbu'
copyright = 'Sukonbu Â© 2025'
enableRobotsTXT = true
generateSocialCard = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
# sectionPagesMenu = 'main' //enables auto generation of menu entries!!!
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
	noClasses = false
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"
[params]
description = 'Welcome to Sukonbu.party'
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
timeZone = "UTC"
[params.author]
	email = "admin@sukonbu.party"
	name = "Sukonbu"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Content"
    url = "/content/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3